"""Enumeracion de categorias de filtros."""

from enum import Enum


class EnumCategoriaFiltro(str, Enum):
    VOLUMEN = "VOLUMEN"
    PRECIO_Y_MOVIMIENTO = "PRECIO_Y_MOVIMIENTO"
    VOLATILIDAD = "VOLATILIDAD"
    MOMENTUM_E_INDICADORES_TECNICOS = "MOMENTUM_E_INDICADORES_TECNICOS"
    TIEMPO_Y_PATRONES_DE_PRECIO = "TIEMPO_Y_PATRONES_DE_PRECIO"
    CARACTERISTICAS_FUNDAMENTALES = "CARACTERISTICAS_FUNDAMENTALES"