"""Enumeracion de todos los filtros disponibles."""

from enum import Enum


class EnumFiltro(str, Enum):
    # Volumen
    VOLUME = "VOLUME"
    AVERAGE_VOLUME = "AVERAGE_VOLUME"
    VOLUMEN_POST_PRE = "VOLUMEN_POST_PRE"
    RELATIVE_VOLUME = "RELATIVE_VOLUME"
    RELATIVE_VOLUME_SAME_TIME = "RELATIVE_VOLUME_SAME_TIME"
    VOLUME_SPIKE = "VOLUME_SPIKE"

    # Precio y Movimiento
    PRECIO = "PRECIO"
    CHANGE = "CHANGE"
    PERCENTAGE_CHANGE = "PERCENTAGE_CHANGE"
    GAP_FROM_CLOSE = "GAP_FROM_CLOSE"
    POSITION_IN_RANGE = "POSITION_IN_RANGE"
    PERCENTAGE_RANGE = "PERCENTAGE_RANGE"
    RANGE_DOLLARS = "RANGE_DOLLARS"
    CROSSING_ABOVE_BELOW = "CROSSING_ABOVE_BELOW"
    DISTANCE_FROM_VWAP_EMA_MA = "DISTANCE_FROM_VWAP_EMA_MA"

    # Volatilidad
    ATR = "ATR"
    ATRP = "ATRP"
    RELATIVE_RANGE = "RELATIVE_RANGE"

    # Momentum e Indicadores Tecnicos
    RSI = "RSI"
    BACK_TO_EMA_ALERT = "BACK_TO_EMA_ALERT"
    THROUGH_EMA_VWAP_ALERT = "THROUGH_EMA_VWAP_ALERT"
    EMA_VWAP_SUPPORT_RESISTANCE = "EMA_VWAP_SUPPORT_RESISTANCE"

    # Tiempo y Patrones de Precio
    HALT = "HALT"
    CONSECUTIVE_CANDLES = "CONSECUTIVE_CANDLES"
    BEARISH_BULLISH_ENGULFING = "BEARISH_BULLISH_ENGULFING"
    FIRST_CANDLE = "FIRST_CANDLE"
    HIGH_LOW_OF_DAY = "HIGH_LOW_OF_DAY"
    NEW_CANDLE_HIGH_LOW = "NEW_CANDLE_HIGH_LOW"
    PERCENTAGE_PULLBACK_HIGHS_LOWS = "PERCENTAGE_PULLBACK_HIGHS_LOWS"
    BREAK_OVER_RECENT_HIGHS_LOWS = "BREAK_OVER_RECENT_HIGHS_LOWS"
    OPENING_RANGE_BREAKDOWN = "OPENING_RANGE_BREAKDOWN"
    OPENING_RANGE_BREAKOUT = "OPENING_RANGE_BREAKOUT"
    PIVOTS = "PIVOTS"
    MINUTOS_IN_MARKET = "MINUTOS_IN_MARKET"

    # Caracteristicas Fundamentales
    FLOAT = "FLOAT"
    SHARES_OUTSTANDING = "SHARES_OUTSTANDING"
    MARKET_CAP = "MARKET_CAP"
    SHORT_INTEREST = "SHORT_INTEREST"
    SHORT_RATIO = "SHORT_RATIO"
    DAYS_UNTIL_EARNINGS = "DAYS_UNTIL_EARNINGS"
    NOTICIAS = "NOTICIAS"
