"""Enumeracion de parametros de filtros."""

from enum import Enum


class EnumParametro(str, Enum):
    # Comun
    CONDICION = "CONDICION"

    # Volumen
    TIPO_VOLUMEN = "TIPO_VOLUMEN"
    TIMEFRAME_VOLUME = "TIMEFRAME_VOLUME"
    TIMEFRAME_AVERAGE_VOLUME = "TIMEFRAME_AVERAGE_VOLUME"
    TIMEFRAME_RELATIVE_VOLUME_PERCENT = "TIMEFRAME_RELATIVE_VOLUME_PERCENT"
    NUMERO_VELAS_VOLUME_SPIKE = "NUMERO_VELAS_VOLUME_SPIKE"
    TIMEFRAME_VOLUME_SPIKE = "TIMEFRAME_VOLUME_SPIKE"
    PROPORCION_VOLUMEN_VOLUME_SPIKE = "PROPORCION_VOLUMEN_VOLUME_SPIKE"

    # Precio y Movimiento
    PUNTO_REFERENCIA_CHANGE = "PUNTO_REFERENCIA_CHANGE"
    TIPO_MEDIDA_CHANGE = "TIPO_MEDIDA_CHANGE"
    TIMEFRAME_PERCENTAGE_CHANGE_PERCENT = "TIMEFRAME_PERCENTAGE_CHANGE_PERCENT"
    FORMATO_GAP_FROM_CLOSE = "FORMATO_GAP_FROM_CLOSE"
    TIMEFRAME_POSITION_IN_RANGE = "TIMEFRAME_POSITION_IN_RANGE"
    TIMEFRAME_PERCENTAGE_RANGE_PERCENT = "TIMEFRAME_PERCENTAGE_RANGE_PERCENT"
    TIMEFRAME_RANGE_DOLLAR = "TIMEFRAME_RANGE_DOLLAR"
    NIVEL_CRUCE_CROSSING_ABOVE_BELOW = "NIVEL_CRUCE_CROSSING_ABOVE_BELOW"
    PERIODO_EMA_CROSSING_ABOVE_BELOW = "PERIODO_EMA_CROSSING_ABOVE_BELOW"
    LINEA_REFERENCIA_DISTANCE_FROM_VWAP_EMA_MA = "LINEA_REFERENCIA_DISTANCE_FROM_VWAP_EMA_MA"
    MODO_DISTANCIA_DISTANCE_FROM_VWAP_EMA_MA = "MODO_DISTANCIA_DISTANCE_FROM_VWAP_EMA_MA"
    PERIODO_LINEA_DISTANCE_FROM_VWAP_EMA_MA = "PERIODO_LINEA_DISTANCE_FROM_VWAP_EMA_MA"

    # Volatilidad
    LONGITUD_ATR = "LONGITUD_ATR"
    MODO_PROMEDIO_MOVIL_ATR = "MODO_PROMEDIO_MOVIL_ATR"
    TIMEFRAME_ATR = "TIMEFRAME_ATR"
    TIMEFRAME_ATRP = "TIMEFRAME_ATRP"
    PERIODO_ATR_ATRP = "PERIODO_ATR_ATRP"
    TIPO_PROMEDIO_MOVIL_ATRP = "TIPO_PROMEDIO_MOVIL_ATRP"
    VALOR_PROMEDIO_MOVIL_ATRP = "VALOR_PROMEDIO_MOVIL_ATRP"

    # Momentum
    PERIODO_RSI = "PERIODO_RSI"
    TIMEFRAME_RSI = "TIMEFRAME_RSI"
    PERIODO_EMA_BACK_TO_EMA = "PERIODO_EMA_BACK_TO_EMA"
    TIMEFRAME_BACK_TO_EMA = "TIMEFRAME_BACK_TO_EMA"
    THROUGH_EMA_VWAP_LINEA_CRUCE = "THROUGH_EMA_VWAP_LINEA_CRUCE"
    THROUGH_EMA_VWAP_PERIODO_EMA = "THROUGH_EMA_VWAP_PERIODO_EMA"
    THROUGH_EMA_VWAP_DIRECCION_ROMPIMIENTO = "THROUGH_EMA_VWAP_DIRECCION_ROMPIMIENTO"
    LINEA_REFERENCIA_EMA_VWAP_SUPPORT = "LINEA_REFERENCIA_EMA_VWAP_SUPPORT"
    PERIODO_EMA_EMA_VWAP_SUPPORT = "PERIODO_EMA_EMA_VWAP_SUPPORT"
    TIPO_ROL_EMA_VWAP_SUPPORT = "TIPO_ROL_EMA_VWAP_SUPPORT"

    # Tiempo y Patrones
    NUMERO_VELAS_CONSECUTIVAS = "NUMERO_VELAS_CONSECUTIVAS"
    TIMEFRAME_CONSECUTIVE_CANDLES = "TIMEFRAME_CONSECUTIVE_CANDLES"
    TIMEFRAME_BEARISH_BULLISH_ENGULFING_CANDLE = "TIMEFRAME_BEARISH_BULLISH_ENGULFING_CANDLE"
    TIPO_PATRON_BEARISH_BULLISH_ENGULFING_CANDLE = "TIPO_PATRON_BEARISH_BULLISH_ENGULFING_CANDLE"
    TIPO_VELA_FIRTS_CANDLE = "TIPO_VELA_FIRTS_CANDLE"
    OPCION_EXTREMO_HIGH_LOW_DAY = "OPCION_EXTREMO_HIGH_LOW_DAY"
    TIMEFRAME_HIGH_LOW_DAY = "TIMEFRAME_HIGH_LOW_DAY"
    OPCION_EXTREMO_NEW_CANDLE = "OPCION_EXTREMO_NEW_CANDLE"
    TIMEFRAME_NEW_CANDLE = "TIMEFRAME_NEW_CANDLE"
    PUNTO_REFERENCIA_PULLBACK = "PUNTO_REFERENCIA_PULLBACK"
    PORCENTAJE_RETROCESO_PULLBACK = "PORCENTAJE_RETROCESO_PULLBACK"
    OPCION_EXTREMO_BREAK_OVER = "OPCION_EXTREMO_BREAK_OVER"
    TIMEFRAME_BREAK_OVER = "TIMEFRAME_BREAK_OVER"
    TIMEFRAME_OPENING_RANGE_BREAKDOWN = "TIMEFRAME_OPENING_RANGE_BREAKDOWN"
    TIMEFRAME_OPENING_RANGE_BREAKOUT = "TIMEFRAME_OPENING_RANGE_BREAKOUT"
    TIMEFRAME_PIVOTS = "TIMEFRAME_PIVOTS"
    MINUTOS_TRANSCURRIDOS = "MINUTOS_TRANSCURRIDOS"
    VALOR_HALT = "VALOR_HALT"

    # Fundamentales
    ESTADO_NOTICIA = "ESTADO_NOTICIA"
