name: CI Signal Processing Service

on:
  push:
    branches: ["master"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build --target test -t signal-processing-service:test .

      - name: Run unit tests
        run: docker run --rm signal-processing-service:test pytest -m "not integration" --tb=short -q

      - name: Run integration tests (API real)
        run: docker run --rm --network host signal-processing-service:test pytest -m "integration" -v -s --tb=short
        continue-on-error: true

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push production image
        run: |
          docker build --target production -t virtud142/metradingplat_signal_processing_service:latest .
          docker push virtud142/metradingplat_signal_processing_service:latest
